### ISSUE TITLE
[#0305] Criar interface para cadastro de estações

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#2]
## Sobre a Tarefa

Criar telas do fluxo de cadastro de estações e seus sensores

> Conforme definido no layout resultado desta task: [FRONT #01](https://github.com/The-Bugger-Ducks/cloud-fox-front/issues/1)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [ ] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [ ] Atende aos critérios de aceite
- [ ] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [ ] Apenas usuários com privilégio de adminstrador ou gerenciador de estação, poderá ter acesso a essas funcionalidades
- [x] Tratar possíveis erros

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias

React, Axios

## Telas

Ativar estação

![Image](https://user-images.githubusercontent.com/58437896/194785551-04dd7a0a-b8c5-4dbb-91e0-3ef00cdd0309.png)

Adicionar parâmetro

![Image](https://user-images.githubusercontent.com/58437896/194785638-83255ba0-8e26-47fb-b7ee-a079fa6d2998.png)


Listagem

![Image](https://user-images.githubusercontent.com/58437896/194785648-f7555407-49ac-4903-8bb3-a6c1e78612c9.png)

**Comment by ThHenrique** [comment]
Devemos melhorar esse processo, não está usual.
