### ISSUE TITLE
[#0804] Criar interface para deletar conta

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#21]
## Sobre a Tarefa

Criar telas do fluxo de exclusão de conta

> Conforme definido no layout resultado desta task: [FRONT #20](https://github.com/The-Bugger-Ducks/cloud-fox-front/issues/20)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Atende ao protótipo desenvolvido

**Comment by MariaGabrielaReis** [comment]
https://www.figma.com/file/BYcRgi17PJWwQMhVc9Kqno/Design?node-id=186%3A2286

**Comment by ThHenrique** [comment]
# Documentação

### Descrição
Tela para perfil do usuário

### Tecnologias
React e Styled Components

## Telas
![image](https://user-images.githubusercontent.com/69374340/190837601-6bd190dd-672b-45c7-8eed-e04da99d66c5.png)
