### ISSUE TITLE
[#1005] Consumir rota para visualização dos parâmetros meteorológicos (dahsboard)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#25]
## Sobre a Tarefa

Consumir rota para cadastro de estações e seus sensores

> Link do [Swagger](). Task backend do endpoint: [BACK #1002](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/22)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [ ] Sem bugs observados / review
- [ ] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tratar possíveis erros
- [x] Notificar usuário (caso erro, ou, sucesso)

**Comment by gioliveirass** [comment]
# Documetação

## Descrição

Foi criado um service para criar a variável que conterá a API a ser utilizada.
![Image](https://user-images.githubusercontent.com/78885451/190875679-8d299903-c277-4906-8ae8-4dadb796df6a.png)

Tendo a variável com a API, foi criada uma classe com métodos para obter as estações. 
![Image](https://user-images.githubusercontent.com/78885451/190875725-705626be-2f5f-40ee-9f7d-44158469db21.png)

Da mesma forma, foi criada uma classe com métodos para obter os dados que aparecerão no Dashboard.  Os dados possuem valores padrão que serão enviados no payload caso nenhum filtro seja aplicados.
![Image](https://user-images.githubusercontent.com/78885451/190875775-4e912947-6895-4dd0-b6ea-e4555d536bd0.png)

## Problemas enfrentados

Atualmente, a rota para pegar os dados de uma única estação não foi desenvolvido. Porém, o front-end já se encontra pronto para consumir a rota através do  método getStationById() assim que possível.

Houve também uma incompatibilidade do axios com a forma na qual o back-end realiza a busca de dados que serão inseridos no dashboard. O axios não aceita enviar o payload, e portanto nenhum dado é retornado pelo back-end. Por conta desse problema, os dados exibidos atualmente são mockados, porém assim que esse imprevisto for superado o método getDashboardData() vai ser atualizado para pegar os dados corretamente.

## Resultado final

A homepage já é capaz de exibir todas as estações ativas.
![Image](https://user-images.githubusercontent.com/78885451/190875997-26de1bb7-9206-4d14-8895-af776e7f950a.png)

O gráfico com dados mockados é exibido dinâmicamente.
![Image](https://user-images.githubusercontent.com/78885451/190876039-3a94fcbf-1221-4a9e-ba42-13b361c5f335.png)

**Comment by ThHenrique** [comment]
Booa
