### ISSUE TITLE
[#0306] Consumir rota para cadastro de estações e seus sensores

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#3]
## Sobre a Tarefa

Consumir rota para cadastro de estações e seus sensores

> Link do [Swagger](). Task backend do endpoint: [BACK #02](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/2)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [ ] Atende aos critérios de aceite
- [ ] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tratar SQL injection dos inputs
- [x] Tratar possíveis erros
- [x] Notificar usuário (caso erro, ou, sucesso)

**Comment by ThHenrique** [comment]
#53 #49 

# Documentação

## Descrição

Consumir rota para cadastro de estações e seus sensores

## Tecnologias

React, Axios

## Implementação

```ts
public async createStation(
    id: string,
    name: string,
    lat: LatLngLiteral,
    lon: LatLngLiteral,
    description: string,
    parameterTypes?: []
  ) {
    try {
      const payload = {
        id: id,
        name: name,
        lat: lat,
        lon: lon,
        description: description,
        parameterTypes: parameterTypes,
      };

      const response = await api.post("/stations", payload);
      return response;
    } catch (error) {
      console.log(error);
      return "error";
    }
  }

```
