### ISSUE TITLE
[#1007] Refatorar dashboard para novo modelo de dados

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#65]
## Sobre a Tarefa

Com base na refatoração do backend, realizar as alterações com base nas alterações do backend

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias

React, Axios

## Interface

```ts

export interface ParamInterface {
  factor: number;
  id: number;
  name: string;
  type: string;
  unit: string;
}

export interface ActiveStationInterface {
  id: string;
  name: string;
  lat: number;
  lon: number;
  description: string;
  startDate: string;
  isActive: boolean;
}

```
