### ISSUE TITLE
[#0311] No formulário: arrumar mapa

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#72]
## Sobre a Tarefa

Arrumar bug do componente de mapa no formulário de criar estação. 

![Image](https://user-images.githubusercontent.com/58437896/197407415-33be0902-b2b4-4f15-b1bd-ca32138328c6.png)

Suponho que o bug está relacionado ao tamanho inicial da caixa onde o componente se encontra, pois sei que o mapa deve inicial ocupando 100% da largura disponível.

Verificar no Stackoverflow e Documentação do Leaflet.

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] O mapa deve iniciar ocupando 100% do tamanho disponível como na Homepage.

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

React e Leaflet.

## Solução para o bug

Utilização da função `map.invalidateSize();` a cada 100ms para redimensionar o container do mapa.

## Ressultado

Os tiles são renderizados corretamente

![Image](https://user-images.githubusercontent.com/78885451/198269061-6e70c57a-8a3f-4a1a-bbf9-df2d006f063b.png)
