### ISSUE TITLE
[#1008] Multiplicar valor pelo fator ao mostrar dados nos gráficos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#73]
## Sobre a Tarefa

Multiplicar valor pelo fator ao mostrar dados nos gráficos

Sem fazer isso os dados informados no gráficos serão incorretos

![Image](https://user-images.githubusercontent.com/58437896/197408410-ac8a322a-dd3d-45e1-b3b3-8b3d64eeb53b.png)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias

HTML, CSS, Axios, React, Hightchart.

## Resultados

Exibindo no valor apresentado no gráfico o valor obtido pela API multiplicado pelo fator.

![Image](https://user-images.githubusercontent.com/78885451/197797974-0dface7a-f840-4f9c-8194-6175d7b8d0de.png)
