### ISSUE TITLE
[#0313] No formulário: redirecionar para dashboard ao concluir

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#74]
## Sobre a Tarefa

Quando criar uma nova estação, redirecionar usuário para a dashboard da estação criada

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias

HTML e React.

## Resultados

Ao cadastrar uma estação o usuário é redirecionado ao Dashboard da estação recém criada, ao invés de abrir o modal de cadastro de parâmetros.
