### ISSUE TITLE
[#1502] Arrumar deploy frontend

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-web#75]
## Sobre a Tarefa

Arrumar deploy do frontend no netlify. 

Até o momento segundo o erro descrito o problema se dá por haver pastas com o mesmo nome porém uma pasta com letra maiúscula e outra pasta minúscula

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [ ] Testado e integrado
- [ ] Sem bugs observados / review
- [ ] Code review
- [ ] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias

Netllify, CSS, HTML.

## Como a correção foi feita

- Foi removida a pasta Handlers que estava duplicada;
- Os caminhos que importavam o conteúdo da pasta Handlers foram corrigidos para importarem o conteúdo da pasta handler,

## Resultado

Todas as verificações do Netlify foram realizadas com sucesso.

![Image](https://user-images.githubusercontent.com/78885451/197753882-460375f9-d29d-4ae2-9244-0fdbd651b02b.png)
