### ISSUE TITLE
[#0312] No formulário: adicionar alerta de sucesso

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#78]
## Sobre a Tarefa

Quando cadastrar uma nova estação, adicionar alerta de sucesso para o usuário.

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação 

## Tecnologias

HTML e React

## Resultados

Alerta quando cadastrar uma estação

![Image](https://user-images.githubusercontent.com/78885451/198287280-be90bd42-c8b8-465a-a98c-2fb2a61d706a.png)
