### ISSUE TITLE
[#0712] Tirar auto login

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#80]
## Sobre a Tarefa

Ao entrar na página de login, remover autologin que é realizado no sistema, ou seja, a ação de realizar login será feita apenas quando o usuário selecionar a opção de login disponível.

![Image](https://user-images.githubusercontent.com/58437896/197408119-48ad3644-1ae5-4be0-901f-69ca50c1beae.png)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by ThHenrique** [comment]
Bloqueado pela questão que o @GabrielCamargoL comentou hoje no discord ?



![Image](https://user-images.githubusercontent.com/58437896/198685177-1d28a3b7-ab00-4100-990c-c8ffb6dd435a.png)

**Comment by MariaGabrielaReis** [comment]
Na verdade estava bloqueada por falta de conhecimento técnico mesmo kkk da biblioteca, do modo de autenticação, enfim. Tirei o auto login removendo as configurações do login com o Google que estavam em um `useEffect`, agora só clicando no botão que essas configurações vão ser criadas e a autententicação vai ser feita
