### ISSUE TITLE
[#1009] Remover filtro na página Dashboard

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#81]
## Sobre a Tarefa

Remover a opção "filtro" da página dasboard de uma estação

![Image](https://user-images.githubusercontent.com/58437896/197408367-1f8aacba-e6fb-4fd3-b4be-4afa72764d47.png)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by MariaGabrielaReis** [comment]
## Documentação
Remoção do ícone de filtro da dasboard de uma estação

|  Antes |  Depois  |
| :------: | :--------: |
| ![image](https://user-images.githubusercontent.com/69374340/197543822-75ea013a-8378-4480-9ad6-2ed397c37630.png) | ![image](https://user-images.githubusercontent.com/69374340/197544126-19539471-8503-4f0a-bd7b-76ff9b7294e2.png)  |
