### ISSUE TITLE
[#2503] Consumir rota para edição da estação

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#82]
## Sobre a Tarefa

Consumir rota para edição de estações

> Link do [Swagger](). Task backend do endpoint: [BACK #1002](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/22)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Notificar usuário (caso erro, ou, sucesso)

**Comment by MariaGabrielaReis** [comment]
## Documentação
Criar modal para edição das informações de uma estação, consumindo o endpoint de edição de estação

```ts
public async editStation(id: string, name: string, lat: LatLngLiteral, lon: LatLngLiteral, description: string) {
   try {
      const payload = {
         id: id,
         name: name,
         lat: lat,
         lon: lon,
         description: description,
      };

      const response = await api.put("/stations/activate/" + id, payload);
      return response;
   } catch (error) {
      console.log(error);
      return "error";
   }
}
```
