### ISSUE TITLE
[#2502] Criar interface de edição de estação

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#83]
## Sobre a Tarefa

Criar modal para edição das informações de uma estação. Serão editados os campos ID (mac address), nome, descrição e localização (lat, lng)

**Obs**: Podemos reutilizar o modal de criação de estação

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by MariaGabrielaReis** [comment]
## Documentação
Criar modal para edição das informações de uma estação. Serão editados os campos ID (mac address), nome, descrição e localização (lat, lng)

![Image](https://user-images.githubusercontent.com/69374340/198696835-41e30b18-442b-45dd-9864-cefb19621898.png)
