### ISSUE TITLE
[#2602] Alterar interface para permitir adicionar mais de um parâmetro a uma estação

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#84]
(selecionando parâmetros já cadastrados)

## Sobre a Tarefa

Conforme [Layout](https://github.com/The-Bugger-Ducks/cloud-fox-web/issues/85) desenvolver nova interface para adicionar mais de um parâmetro a uma estação

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias

HTML, CSS, Material-UI, React e Axios.

## Resultados

### Tabela de parâmetros existentes

A tabela de parâmetros existentes permmite o usuário selecionar quais parâmetros já cadastrados ele deseja adicionar a uma estação. Isso evita que vários parâmetros semelhantes sejam cadastrados.

![Image](https://user-images.githubusercontent.com/78885451/199802435-6b2a91ce-635d-4c27-8da9-6e5dafdff2b1.png)

### Formulário de adição de parâmetros

O formulário de adição de estação é contido em um accordion, garantido que o usuário só veja o parâmetro se realmente for necessário.

![Image](https://user-images.githubusercontent.com/78885451/199803043-0c8a58e8-004e-4836-991a-6980226c6063.png)

### Lista de parâmetros a serem cadastrados

O formulário permite que os usuários adicionem quantos parâmetros desejarem. A lista de cadastro fica ao final do formulário.

Exemplo sem parâmetros na lista:

![Image](https://user-images.githubusercontent.com/78885451/199802640-5ada9b3a-522e-4942-a91c-e1677826484a.png)

Exemplo com parâmetros na lista:

![Image](https://user-images.githubusercontent.com/78885451/199802577-7af79a59-8b3c-49cd-a0f1-3721476d38b2.png)
