### ISSUE TITLE
[#2604] Mudar para select na escolha da unidade de medida da criação de parâmetros

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#87]
## Sobre a Tarefa

Conforme [pesquisa realizada](https://github.com/The-Bugger-Ducks/cloud-fox-web/issues/86) utilizar medidas em um **select** para que o usuário selecione a unidade de medida desejável.

Adicionar opção OUTROS, para permitir que usuário adicione (escrevendo) uma medida diferente das opções da lista.

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação 

## Tecnologias

HTML, CSS, Styled-component

## Resultados

Select para selecionar a unidade de medida:

![Image](https://user-images.githubusercontent.com/78885451/198292996-74749bed-7100-486c-aad7-4fc3a716d76c.png)
