### ISSUE TITLE
[#2605] Botões fixos na criação de parâmetros

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#88]
## Sobre a Tarefa

Arrumar tamanho fixo do botão para evitar bugs na interface.

Task igual a [botão criação de estação](https://github.com/The-Bugger-Ducks/cloud-fox-web/issues/79)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by MariaGabrielaReis** [comment]
## Documentação
Ajuste do tamanho dos botões do formulário

|  Antes |  Depois  |
| :------: | :--------: |
| ![image](https://user-images.githubusercontent.com/69374340/198328673-e0313abd-645a-4b23-ad6b-0a830b7a250b.png) | ![image](https://user-images.githubusercontent.com/69374340/198328599-4284c1c8-d3e2-4c88-bbd4-42ec4dc79b21.png) |
