### ISSUE TITLE
Adicionar loading

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#89]
## Sobre a Tarefa

Adicior loading nas requisições realizadas no frontend

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

Lottie, React, Styled-Component, HTML

## Resultados

Homepage:

![Image](https://user-images.githubusercontent.com/78885451/198699836-abbecb82-8cd8-42bc-973d-6511df78efff.png)

Dashboard:

![Image](https://user-images.githubusercontent.com/78885451/198699927-4ebe0f0b-ddd2-4119-928d-024a127db08d.png)
