### ISSUE TITLE
Melhorar responsividade da home até 1024px

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-web#90]
## Sobre a Tarefa

Melhorar responsividade das homepage para que os card das estações e itens da página seja suportado até 1024px

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

HTML, CSS, Styled-component, React.

## Resultados

Telas de diferentes tamanhos:

![Image](https://user-images.githubusercontent.com/78885451/198284336-dad1562d-cfbd-497c-a385-7300eea162db.png)
![Image](https://user-images.githubusercontent.com/78885451/198284408-f0409470-8a48-4abb-8e46-0499e1e05be3.png)

Modals de cadastro:

![Image](https://user-images.githubusercontent.com/78885451/198285319-075dbaac-f426-44b0-acfc-c693e96c555e.png)
![Image](https://user-images.githubusercontent.com/78885451/198285417-827c2432-5b89-40ef-a92d-29cd5c34736e.png)
